// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type siderspGlobalCfg struct {
	_               structs.HostLayout
	AllEnabledRules siderspMaskT
}

type siderspIpv4LpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type siderspMaskT struct {
	_    structs.HostLayout
	Bits [4]uint64
}

type siderspRuleMeta struct {
	_            structs.HostLayout
	RuleId       uint32
	Priority     uint32
	Enabled      uint32
	RequiredMask uint32
	Action       uint32
}

// loadSidersp returns the embedded CollectionSpec for sidersp.
func loadSidersp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SiderspBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sidersp: %w", err)
	}

	return spec, err
}

// loadSiderspObjects loads sidersp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*siderspObjects
//	*siderspPrograms
//	*siderspMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSiderspObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSidersp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// siderspSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siderspSpecs struct {
	siderspProgramSpecs
	siderspMapSpecs
	siderspVariableSpecs
}

// siderspProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siderspProgramSpecs struct {
	XdpSidersp *ebpf.ProgramSpec `ebpf:"xdp_sidersp"`
}

// siderspMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siderspMapSpecs struct {
	DstPortIndexMap *ebpf.MapSpec `ebpf:"dst_port_index_map"`
	DstPrefixLpmMap *ebpf.MapSpec `ebpf:"dst_prefix_lpm_map"`
	EventRingbuf    *ebpf.MapSpec `ebpf:"event_ringbuf"`
	FeatureIndexMap *ebpf.MapSpec `ebpf:"feature_index_map"`
	GlobalCfgMap    *ebpf.MapSpec `ebpf:"global_cfg_map"`
	RuleIndexMap    *ebpf.MapSpec `ebpf:"rule_index_map"`
	SrcPortIndexMap *ebpf.MapSpec `ebpf:"src_port_index_map"`
	SrcPrefixLpmMap *ebpf.MapSpec `ebpf:"src_prefix_lpm_map"`
	StatsMap        *ebpf.MapSpec `ebpf:"stats_map"`
	VlanIndexMap    *ebpf.MapSpec `ebpf:"vlan_index_map"`
}

// siderspVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siderspVariableSpecs struct {
}

// siderspObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSiderspObjects or ebpf.CollectionSpec.LoadAndAssign.
type siderspObjects struct {
	siderspPrograms
	siderspMaps
	siderspVariables
}

func (o *siderspObjects) Close() error {
	return _SiderspClose(
		&o.siderspPrograms,
		&o.siderspMaps,
	)
}

// siderspMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSiderspObjects or ebpf.CollectionSpec.LoadAndAssign.
type siderspMaps struct {
	DstPortIndexMap *ebpf.Map `ebpf:"dst_port_index_map"`
	DstPrefixLpmMap *ebpf.Map `ebpf:"dst_prefix_lpm_map"`
	EventRingbuf    *ebpf.Map `ebpf:"event_ringbuf"`
	FeatureIndexMap *ebpf.Map `ebpf:"feature_index_map"`
	GlobalCfgMap    *ebpf.Map `ebpf:"global_cfg_map"`
	RuleIndexMap    *ebpf.Map `ebpf:"rule_index_map"`
	SrcPortIndexMap *ebpf.Map `ebpf:"src_port_index_map"`
	SrcPrefixLpmMap *ebpf.Map `ebpf:"src_prefix_lpm_map"`
	StatsMap        *ebpf.Map `ebpf:"stats_map"`
	VlanIndexMap    *ebpf.Map `ebpf:"vlan_index_map"`
}

func (m *siderspMaps) Close() error {
	return _SiderspClose(
		m.DstPortIndexMap,
		m.DstPrefixLpmMap,
		m.EventRingbuf,
		m.FeatureIndexMap,
		m.GlobalCfgMap,
		m.RuleIndexMap,
		m.SrcPortIndexMap,
		m.SrcPrefixLpmMap,
		m.StatsMap,
		m.VlanIndexMap,
	)
}

// siderspVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSiderspObjects or ebpf.CollectionSpec.LoadAndAssign.
type siderspVariables struct {
}

// siderspPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSiderspObjects or ebpf.CollectionSpec.LoadAndAssign.
type siderspPrograms struct {
	XdpSidersp *ebpf.Program `ebpf:"xdp_sidersp"`
}

func (p *siderspPrograms) Close() error {
	return _SiderspClose(
		p.XdpSidersp,
	)
}

func _SiderspClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sidersp_bpfel.o
var _SiderspBytes []byte
